services:
  # Define the database service
  sportsappDatabase:
    image: mysql:8.0
    container_name: sportsappDatabase
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SportsApp
      MYSQL_USER: sportuser
      MYSQL_PASSWORD: sportpassword
    ports:
      - "3306:3306"
    networks:
      - sport_network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    container_name: frontend
    build:
      context: ./SportsApp.Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - sport_network
    depends_on:
      - sportsapp_api
  
  sportsapp_api:
    container_name: sportsapp_api
    build:
      context: ./SportsApp.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      #- "8081:8081"
    restart: unless-stopped
    command: ["dotnet", "ef", "database", "update"]
    networks:
      - sport_network
    depends_on:
      sportsappDatabase:
        condition: service_healthy
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - SmtpSettings__Server=SmtpSettings__Server
     - SmtpSettings__Port=SmtpSettings__Port
     - SmtpSettings__SenderName=SmtpSettings__SenderName
     - SmtpSettings__SenderEmail=SmtpSettings__SenderEmail
     - SmtpSettings__Username=SmtpSettings__Username
     - SmtpSettings__Password=SmtpSettings__Password
     - SmtpSettings__Subject=SmtpSettings__Subject
     - SmtpSettings__UseSSL=true

  sport_web_proxy:
    container_name: sport_web_proxy
    build:
      context: ./proxi
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"
    depends_on:
      - frontend
      - sportsapp_api
    networks:
      - sport_network
      - nginx_proxi_default

networks:
  sport_network:
    name: sport_network
  nginx_proxi_default:

volumes:
  mysql-data:
  app_images:
  static_data:
  media_data:
